config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  resources :merchants
  devise_for :users, skip: [:registrations]
  resources :users, except: :create
  post 'create_user' => 'users#create', as: :create_user      

  root to: 'merchants#index'
  match '/users',   to: 'users#index',   via: 'get'
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  validates_presence_of :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable, :lockable
  validates_presence_of :first_name, :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]

	def index
    @merchants = Merchant.all
  end

	def new
		@merchant = Merchant.new
	end

	def create
		@merchant = Merchant.new(merchant_params)

		if @merchant.save
			redirect_to "/merchants", notice: 'The merchant was created successfully'
		else
			render :new
		end
	end

	def show
	end

  def edit
  end

  def update
    if @merchant.update(merchant_params)
      redirect_to "/merchants", notice: 'The merchant was updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @merchant.delete
    redirect_to merchants_path, notice: 'The merchant was deleted successfully'
  end

	private

	  def merchant_params
	  	params.require(:merchant).permit(:company, :production_parent_mid, :sandbox_parent_mid, :company_nickname, :main_contact, :main_contact_email, :franchise_or_smb, :has_global_db, :has_memberships, :has_migration, :has_dedicated_infrastructure, :has_enterprise_billing, :notes, :rollout_planner_link, :project_plan_link, :drive_folder_link, :training, :timezone)
	  end

	  def set_merchant
	  	@merchant = Merchant.find(params[:id])
	  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize_admin, only: :create

  before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index
    @users = User.all
  end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to edit_user_path, notice: 'The user was created successfully'
		else
			render :new
		end
	end

	def show
	end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to edit_user_path, notice: 'The user was updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @user.delete
    redirect_to users_path, notice: 'The user was deleted successfully'
  end


private

  def authorize_admin
    return unless !current_user.type = AdminUser
    redirect_to root_path, alert: 'Admins only!'
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :type)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(path)
    "active" if current_page?(path)
  end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render 'shared/nav' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/merchants/_form.html.erb
<%= simple_form_for @merchant do |f| %>

  <%=  f.input :production_parent_mid, label:"Production Parent Account MID"%>
  <%=  f.input :sandbox_parent_mid, label:"Sandbox Parent Account MID" %>
  <%=  f.input :company, label:"Company Name"%>
  <%=  f.input :company_nickname, label:"Company Nickname" %>
  <%=  f.input :main_contact, label:"Contact Name" %>
  <%=  f.input :main_contact_email, label:"Contact Email" %>
  <%=  f.input :franchise_or_smb, label:"Franchise or SMB" %>
  <%=  f.input :has_global_db, as: :radio_buttons, label:"Global DB" %>
  <%=  f.input :has_memberships, as: :radio_buttons, label:"Memberships" %>
  <%=  f.input :has_migration, as: :radio_buttons, label:"Data Migration" %>
  <%=  f.input :has_dedicated_infrastructure, as: :radio_buttons, label:"Dedicated Infrastructure" %>
  <%=  f.input :has_enterprise_billing, as: :radio_buttons, label:"Enterprise Billing" %>
  <%=  f.input :notes, label:"Notes" %>
  <%=  f.input :rollout_planner_link %>
  <%=  f.input :project_plan_link %>
  <%=  f.input :drive_folder_link %>
  <%=  f.input :training, label:"Training Requirements" %>
  <%=  f.input :timezone %>

  <%= f.submit 'Save' %>

<% end %>

app/views/merchants/_merchant.html.erb
<% @merchants.each do |merchant| %>
  <tr>
    <td style ="word-wrap:break-word;"><%= merchant.company%></td>
    <td style ="word-wrap:break-word;"><%= merchant.production_parent_mid%></td>
    <td style ="word-wrap:break-word;"><%= merchant.sandbox_parent_mid%></td>
    <td style ="word-wrap:break-word;"><%= merchant.timezone%></td>
    <td style ="word-wrap:break-word;"><%= merchant.main_contact%></td>
    <td> <%= link_to 'Rollout', "https://#{merchant.rollout_planner_link}"  %></td>
    <td> <%= link_to 'Project', "https://#{merchant.project_plan_link}"  %></td>
    <td> <%= link_to 'Folder', "https://#{merchant.drive_folder_link}"  %></td>
    <td><%= link_to edit_merchant_path(merchant) do %>
      <span class="fa fa-edit"></span>
      <% end %>            <%= link_to merchant_path(merchant), method: :delete, id: "delete_merchant_#{merchant.id}_from_index", data: { confirm: 'Are you sure you want to delete this merchant? This cannot be undone!' } do %>
      <span class="fa fa-trash">
      </span>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/merchants/edit.html.erb
<h1>Edit Merchant</h1>
<%= render 'form' %>

app/views/merchants/index.html.erb
<table class="table table-striped table-hover" style="table-layout: fixed; width: 100%">
	<thead>
			<th>
        Company Name
      </th>
      <th>
        Production Parent MID
      </th>
      <th>
        Sandbox Parent MID
      </th>
      <th>
        Timezone
      </th>
      <th>
        Main Contact
      </th>
      <th>
        Rollout Planner Link
      </th>
      <th>
        Project Plan Link
      </th>
      <th>
        Drive Folder Link
      </th>
	</thead>
  <tbody>
    <%= render "merchant" %>
  </tbody>
</table>

app/views/merchants/new.html.erb
<h1>Create New Merchant</h1>
<br>
<%= render 'form' %>

app/views/merchants/show.html.erb
<%= @merchant.inspect %>

app/views/shared/_nav.html.erb
<div class="row">
		<div class="col-md-12">
      <ul class="custom-nav nav nav-tabs">
				<li class="nav-item">
					<a class="nav-link <%= active?(merchants_path) %>" href="/merchants">Merchant List</a>
				</li>
				<li class="nav-item">
					<a class="nav-link <%= active?(new_merchant_path) %>" href="/merchants/new">New Merchant</a>
				</li>
				<li class="nav-item">
					<a class="nav-link <%= active?("/users") %>" href="/users">Users</a>
				</li>
        <li class="nav-item dropdown ml-md-auto">
          <a class="nav-item" id="navbarDropdownMenuLink">
            <% if user_signed_in? %>
              <a class="dropdown-item"><%= link_to('Logout', destroy_user_session_path, method: :delete) %></a>
            <% else %>
              <a class="dropdown-item"><%= link_to('Login', new_user_session_path) %></a>
            <% end %>
          </a>
        </li>
  		</ul>
  	</div>
  </div>

app/views/users/_form.html.erb
<%= simple_form_for User.new, url: create_user_path do |f|  %>

  <%=  f.input :first_name %>
  <%=  f.input :last_name %>
  <%=  f.input :email %>
  <%=  f.input :password %>
  <%=  f.input :password_confirmation %>

  <%= f.submit 'Save' %>

<% end %>

app/views/users/index.html.erb
<h3>Users</h3>

<table class="table table-striped table-hover">
	<thead>
			<th>
        First Name
      </th>
      <th>
        Last Name
      </th>
      <th>
        Email
      </th>
      <th>
        User Type
      </th>
      	</thead>
  <tbody>
      <% @users.each do |user| %>
      <tr>
        <td style ="word-break:break-all;"><%= user.first_name %></td>
        <td style ="word-break:break-all;"><%= user.last_name %></td>
        <td style ="word-break:break-all;"><%= user.email %></td>
        <td style ="word-break:break-all;"><%= user.type %></td>
        <td><%= link_to 'Delete', user_path(user), method: :delete, id: "delete_user_#{user.id}_from_index", data: { confirm: 'Are you sure you want to delete this user? This cannot be undone!' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Create New User</h1>
<%= render 'form' %>